from typing import Callable, Dict, NamedTuple, Optional, TYPE_CHECKING

import random

from BaseClasses import Item, ItemClassification, MultiWorld 
if TYPE_CHECKING:
    from . import GrimDawnWorld
else:
    GrimDawnWorld = object

baseId = 219990

class GrimDawnItem(Item):
    game = "Grim Dawn"

class GrimDawnItemData(NamedTuple):
    code: Optional[int] = None
    type: ItemClassification = ItemClassification.filler
    quantity: int = 1
    can_create: Callable[[MultiWorld, int], bool] = lambda multiworld, player: True

_item_data_list: list[tuple[str,ItemClassification,int,int,Optional[Callable[[GrimDawnWorld], bool]]]] = [
    #Item Name                                              Progression, useful, or filler                   Item ID                       Amount                        Logic to determine if item is created and added to the pool
    ("Strange Key",                                         ItemClassification.progression,                  219990,                       1,                            None),
    ("5 Scrap",                                             ItemClassification.progression,                  219991,                       1,                            None),
    ("Flooded Passage Destroy Blockade",                    ItemClassification.progression,                  219992,                       1,                            None),
    ("Lower Crossing Destroy Blockade",                     ItemClassification.progression,                  219993,                       1,                            None),
    ("East Marsh Bridge Repair",                            ItemClassification.progression,                  219994,                       1,                            None),
    ("Warden Boss Door Unlock",                             ItemClassification.progression,                  219995,                       1,                            lambda world: (world.options.progressive_progression.value == False)),
    ("Arkovia Bridge Repair",                               ItemClassification.progression,                  219996,                       1,                            lambda world: (world.options.goal.value >= 2) and (world.options.progressive_progression.value == False)),
    ("Arkovian Foothills Destroy Barricade",                ItemClassification.progression,                  219997,                       1,                            lambda world: (world.options.goal.value >= 2) and (world.options.progressive_progression.value == False)),
    ("New Harbor Destroy Barricade",                        ItemClassification.progression,                  219998,                       1,                            lambda world: (world.options.goal.value >= 2) and ((world.options.secret_chest.value == 1))),
    ("Prospector's Trail Destroy Barricade",                ItemClassification.progression,                  219999,                       1,                            lambda world: (world.options.goal.value >= 2)),
    ("Twin Falls Bridge Repair",                            ItemClassification.progression,                  220000,                       1,                            lambda world: (world.options.goal.value >= 2)),
    ("Homestead Side Doors Unlock",                         ItemClassification.progression,                  220001,                       1,                            lambda world: (world.options.goal.value >= 2)),
    ("Rotting Croplands Destroy South Blockade",            ItemClassification.progression,                  220002,                       1,                            lambda world: (world.options.goal.value >= 2)),
    ("Rotting Croplands Destroy North Blockade",            ItemClassification.progression,                  220003,                       1,                            lambda world: (world.options.goal.value >= 2) and ((world.options.one_shot.value == 1))),
    ("Royal Hive Queen Door Unlock",                        ItemClassification.progression,                  220004,                       1,                            lambda world: (world.options.goal.value >= 2)),
    ("Conflagration Destroy Barricade",                     ItemClassification.progression,                  220005,                       1,                            lambda world: (world.options.goal.value >= 2) and ((world.options.forbidden_dungeons.value == 1))),
    ("Homestead Main Doors Unlock",                         ItemClassification.progression,                  220006,                       1,                            lambda world: (world.options.goal.value >= 3) and (world.options.progressive_progression.value == False)),
    ("Witch Gods Temple Unlock",                            ItemClassification.progression,                  220007,                       1,                            lambda world: (world.options.goal.value >= 3)),
    ("Fort Ikon Gate Unlock",                               ItemClassification.progression,                  220008,                       1,                            lambda world: (world.options.goal.value >= 3) and (world.options.progressive_progression.value == False)),
    ("Fort Ikon Destroy Blockade",                          ItemClassification.progression,                  220009,                       1,                            lambda world: (world.options.goal.value >= 3) and (world.options.progressive_progression.value == False)),
    ("Old Grove Bridge Repair",                             ItemClassification.progression,                  220010,                       1,                            lambda world: (world.options.goal.value >= 2) and (world.options.dlc_fg.value == 1)),
    ("Necropolis Bridge Repair",                            ItemClassification.progression,                  220011,                       1,                            lambda world: (world.options.goal.value >= 3)),
    ("Tomb of the Watchers Door Unlock",                    ItemClassification.progression,                  220012,                       1,                            lambda world: (world.options.goal.value >= 3) and (world.options.progressive_progression.value == False)),
    ("Loghorrean Seal Unlock",                              ItemClassification.progression,                  220013,                       1,                            lambda world: (world.options.goal.value >= 3) and (world.options.progressive_progression.value == False)),
    ("Gloomwald Destroy Blockade",                          ItemClassification.progression,                  220014,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Nane's Hideout Destroy Barricade",                    ItemClassification.progression,                  220015,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Ugdenbog Destroy Barricade",                          ItemClassification.progression,                  220016,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Forlorn Cellar Unlock",                               ItemClassification.progression,                  220017,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Altar of Rattosh Portal",                             ItemClassification.progression,                  220018,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Arcane Lens",                                         ItemClassification.filler,                       220019,                       0,                            lambda world: False),
    ("Malmouth Sewers Destroy Blockade",                    ItemClassification.progression,                  220020,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Candle District Door Unlock",                         ItemClassification.progression,                  220021,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Steelcap District Door Unlock",                       ItemClassification.progression,                  220022,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Malmouth Harbor Destroy Barricade",                   ItemClassification.progression,                  220023,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Crown Hill Destroy Gates",                            ItemClassification.progression,                  220024,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Crown Hill Open Flesh Barrier",                       ItemClassification.progression,                  220025,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Fleshworks Open Flesh Barrier",                       ItemClassification.progression,                  220026,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.progressive_progression.value == False) and (world.options.dlc_aom.value == 1)),
    ("Wightmire Bridge Repair",                             ItemClassification.useful,                       220027,                       1,                            None),
    ("Malmouth Harbor Shortcut",                            ItemClassification.useful,                       220028,                       1,                            lambda world: (world.options.goal.value >= 4) and (world.options.dlc_aom.value == 1)),
    ("Skill Points",                                        ItemClassification.useful,                       220029,                       0,                            lambda world: False),
    ("Aether Crystals",                                     ItemClassification.filler,                       220030,                       0,                            lambda world: False),
    ("Frozen Heart",                                        ItemClassification.filler,                       220031,                       0,                            lambda world: False),
    ("Black Tallow",                                        ItemClassification.filler,                       220032,                       0,                            lambda world: False),
    ("Blessed Steel",                                       ItemClassification.filler,                       220033,                       0,                            lambda world: False),
    ("Chipped Claw",                                        ItemClassification.filler,                       220034,                       0,                            lambda world: False),
    ("Hallowed Fang",                                       ItemClassification.filler,                       220035,                       0,                            lambda world: False),
    ("Imbued Silver",                                       ItemClassification.filler,                       220036,                       0,                            lambda world: False),
    ("Spellwoven Threads",                                  ItemClassification.filler,                       220037,                       0,                            lambda world: False),
    ("Ectoplasm",                                           ItemClassification.filler,                       220038,                       0,                            lambda world: False),
    ("Reinforced Shell",                                    ItemClassification.filler,                       220039,                       0,                            lambda world: False),
    ("Riftstone",                                           ItemClassification.filler,                       220040,                       0,                            lambda world: False),
    ("Aether Soul",                                         ItemClassification.filler,                       220041,                       0,                            lambda world: False),
    ("Severed Claw",                                        ItemClassification.filler,                       220042,                       0,                            lambda world: False),
    ("Spined Carapace",                                     ItemClassification.filler,                       220043,                       0,                            lambda world: False),
    ("Wardstone",                                           ItemClassification.filler,                       220044,                       0,                            lambda world: False),
    ("Extra EXP",                                           ItemClassification.filler,                       220045,                       0,                            lambda world: False),
    ("Relic - Ancestor",                                    ItemClassification.useful,                       220046,                       0,                            lambda world: False),
    ("Relic - Blight",                                      ItemClassification.useful,                       220047,                       0,                            lambda world: False),
    ("Relic - Equilibrium",                                 ItemClassification.useful,                       220048,                       0,                            lambda world: False),
    ("Relic - Conflagration",                               ItemClassification.useful,                       220049,                       0,                            lambda world: False),
    ("Relic - Desolation",                                  ItemClassification.useful,                       220050,                       0,                            lambda world: False),
    ("Relic - Endurance",                                   ItemClassification.useful,                       220051,                       0,                            lambda world: (world.options.dlc_fg.value == 1)),
    ("Relic - Haunt",                                       ItemClassification.useful,                       220052,                       0,                            lambda world: False),
    ("Relic - Sanctuary",                                   ItemClassification.useful,                       220053,                       0,                            lambda world: False),
    ("Relic - Guile",                                       ItemClassification.useful,                       220054,                       0,                            lambda world: False),
    ("Relic - Juggernaut",                                  ItemClassification.useful,                       220055,                       0,                            lambda world: False),
    ("Relic - Mortality",                                   ItemClassification.useful,                       220056,                       0,                            lambda world: (world.options.dlc_aom.value == 1)),
    ("Relic - Slaughter",                                   ItemClassification.useful,                       220057,                       0,                            lambda world: False),
    ("Relic - Vendetta",                                    ItemClassification.useful,                       220058,                       0,                            lambda world: (world.options.dlc_aom.value == 1)),
    ("Skeleton Keys",                                       ItemClassification.useful,                       220059,                       5,                            lambda world: (world.options.goal.value >= 1) and ((world.options.forbidden_dungeons.value == 1))),
    ("Forbidden Door Unlock",                               ItemClassification.progression,                  220060,                       1,                            lambda world: (world.options.goal.value >= 1) and ((world.options.forbidden_dungeons.value == 1))),
    ("Vanguard of the Three Door Unlock",                   ItemClassification.progression,                  220061,                       1,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1) and (world.options.progressive_progression.value == False)),
    ("Valley of the Chosen Destroy Barrier",                ItemClassification.progression,                  220062,                       1,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1) and ((world.options.forbidden_dungeons.value == 1))),
    ("Path of Ascension Destroy Barrier",                   ItemClassification.progression,                  220063,                       1,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1) and (world.options.progressive_progression.value == False)),
    ("Eldritch Gate Destroy Barrier",                       ItemClassification.progression,                  220064,                       1,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1) and (world.options.progressive_progression.value == False)),
    ("25K Iron Bits",                                       ItemClassification.filler,                       220065,                       0,                            lambda world: False),
    ("Eldritch Essence",                                    ItemClassification.useful,                       220066,                       3,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1)),
    ("Devil's Crossing Revered",                            ItemClassification.progression,                  220067,                       1,                            lambda world: ((world.options.faction.value == 1))),
    ("Rovers Revered",                                      ItemClassification.progression,                  220068,                       1,                            lambda world: (world.options.goal.value >= 2) and ((world.options.faction.value == 1))),
    ("Homestead Revered",                                   ItemClassification.progression,                  220069,                       1,                            lambda world: (world.options.goal.value >= 3) and ((world.options.faction.value == 1))),
    ("Death's Vigil - Kymon's Chosen Revered",              ItemClassification.progression,                  220070,                       1,                            lambda world: (world.options.goal.value >= 3) and ((world.options.faction.value == 1))),
    ("Black Legion Revered",                                ItemClassification.progression,                  220071,                       1,                            lambda world: (world.options.goal.value >= 3) and ((world.options.faction.value == 1))),
    ("Coven of Ugdenbog Revered",                           ItemClassification.progression,                  220072,                       1,                            lambda world: (world.options.goal.value >= 4) and ((world.options.faction.value == 1))),
    ("Malmouth Resistance Revered",                         ItemClassification.progression,                  220073,                       1,                            lambda world: (world.options.goal.value >= 4) and ((world.options.faction.value == 1))),
    ("Witch God Cults Revered",                             ItemClassification.progression,                  220074,                       1,                            lambda world: (world.options.goal.value >= 1) and (world.options.dlc_fg.value == 1) and ((world.options.faction.value == 1))),
    ("Aetherial Emblem",                                    ItemClassification.progression,                  220075,                       0,                            None),
    ("Progressive Main Campaign",                           ItemClassification.progression,                  220076,                       0,                            None),
    ("Progressive Forgotten Gods",                          ItemClassification.progression,                  220077,                       0,                            None),
    ("Progressive Ashes of Malmouth",                       ItemClassification.progression,                  220078,                       0,                            None),
    ("Kilrian's Shattered Soul",                            ItemClassification.filler,                       220079,                       0,                            None),
    ("Dread Skull",                                         ItemClassification.filler,                       220080,                       0,                            None),
    ("Hallowed Ground",                                     ItemClassification.filler,                       220081,                       0,                            None),
    ("Mark of Mogdrogen",                                   ItemClassification.filler,                       220082,                       0,                            None),
    ("Ancient Armor Plate",                                 ItemClassification.filler,                       220083,                       0,                            None),
    ("Prismatic Diamond",                                   ItemClassification.filler,                       220084,                       0,                            None),
    ("Arcane Spark",                                        ItemClassification.filler,                       220085,                       0,                            None),
    ("Shard of Beronath",                                   ItemClassification.filler,                       220086,                       0,                            None),
    ("Bloody Whetstone",                                    ItemClassification.filler,                       220087,                       0,                            None),
    ("Chains of Oleron",                                    ItemClassification.filler,                       220088,                       0,                            None),
    ("Devil-Touched Ammo",                                  ItemClassification.filler,                       220089,                       0,                            None),
    ("Haunted Steel",                                       ItemClassification.filler,                       220090,                       0,                            None),
    ("Attuned Lodestone",                                   ItemClassification.filler,                       220091,                       0,                            None),
    ("Bindings of Bysmiel",                                 ItemClassification.filler,                       220092,                       0,                            None),
    ("Mark of Dreeg",                                       ItemClassification.filler,                       220093,                       0,                            None),
    ("Mark of the Myrmidon",                                ItemClassification.filler,                       220094,                       0,                            None),
    ("Oleron's Blood",                                      ItemClassification.filler,                       220095,                       0,                            None),
    ("Silvercore Bolts",                                    ItemClassification.filler,                       220096,                       0,                            None),
    ("Symbol of Solael",                                    ItemClassification.filler,                       220097,                       0,                            None),
    ("Unholy Inscription",                                  ItemClassification.filler,                       220098,                       0,                            None),
    ("Spellwoven Threads",                                  ItemClassification.filler,                       220099,                       0,                            None),
]

relic_table = [
    "Relic - Ancestor",
	"Relic - Blight",
	"Relic - Equilibrium",
	"Relic - Conflagration",
	"Relic - Desolation",
	"Relic - Endurance",
	"Relic - Haunt",
	"Relic - Sanctuary",
	"Relic - Guile",
	"Relic - Juggernaut",
	"Relic - Mortality",
	"Relic - Slaughter",
	"Relic - Vendetta",
]

_filler_data_table={
    "Extra EXP":34,
    "Skill Points":12,
    "25K Iron Bits":12,
    "Relic":5,
    "Aether Crystals":1,
    "Frozen Heart":1,
    "Black Tallow":1,
    "Blessed Steel":1,
    "Chipped Claw":1,
    "Hallowed Fang":1,
    "Imbued Silver":1,
    "Spellwoven Threads":1,
    "Ectoplasm":1,
    "Reinforced Shell":1,
    "Riftstone":1,
    "Aether Soul":1,
    "Arcane Lens":1,
    "Severed Claw":1,
    "Spined Carapace":1,
    "Wardstone":1,
    "Kilrian's Shattered Soul":1,
    "Dread Skull":1,
    "Hallowed Ground":1,
    "Mark of Mogdrogen":1,
    "Ancient Armor Plate":1,
    "Prismatic Diamond":1,
    "Arcane Spark":1,
    "Shard of Beronath":1,
    "Bloody Whetstone":1,
    "Chains of Oleron":1,
    "Devil-Touched Ammo":1,
    "Haunted Steel":1,
    "Attuned Lodestone":1,
    "Bindings of Bysmiel":1,
    "Mark of Dreeg":1,
    "Mark of the Myrmidon":1,
    "Oleron's Blood":1,
    "Silvercore Bolts":1,
    "Symbol of Solael":1,
    "Unholy Inscription":1,
    "Spellwoven Threads":1
}

item_name_groups = ({
    "Relic": {      "Relic - Ancestor",
                	"Relic - Blight",
	                "Relic - Equilibrium",
	                "Relic - Conflagration",
	                "Relic - Desolation",
	                "Relic - Endurance",
	                "Relic - Haunt",
	                "Relic - Sanctuary",
	                "Relic - Guile",
	                "Relic - Juggernaut",
	                "Relic - Mortality",
	                "Relic - Slaughter",
	                "Relic - Vendetta",},
    "Major Progression": {"Progressive Main Campaign",
                          "Progressive Forgotten Gods",
                          "Progressive Ashes of Malmouth",
                          "Warden Boss Door Unlock",
                          "Arkovia Bridge Repair",
                          "Arkovian Foothills Destroy Barricade",
                          "Homestead Main Doors Unlock",
                          "Fort Ikon Gate Unlock",
                          "Tomb of the Watchers Door Unlock",
                          "Loghorrean Seal Unlock",
                          "Gloomwald Destroy Blockade",
                          "Altar of Rattosh Portal",
                          "Steelcap District Door Unlock",
                          "Crown Hill Destroy Gates",
                          "Crown Hill Open Flesh Barrier",
                          "Fleshworks Open Flesh Barrier",},
    "Side Progression": {"Lower Crossing Destroy Blockade",
                         "East Marsh Bridge Repair",
                         "Prospector's Trail Destroy Barricade",
                         "Twin Falls Bridge Repair",
                         "Homestead Side Doors Unlock",
                         "Royal Hive Queen Door Unlock",
                         "Conflagration Destroy Barricade",
                         "Witch Gods Temple Unlock",
                         "Forbidden Door Unlock",
                         "Valley of the Chosen Destroy Barrier",},
})

filler_table = [k for k,v in _filler_data_table.items()]
filler_weights = [v for k,v in _filler_data_table.items()]

def get_unique_relic(world: "GrimDawnWorld") -> str:
    if len(world.local_relic_table) > 0:
        return world.local_relic_table.pop()
    else:
        return ""


item_data_table: Dict[str, GrimDawnItemData] = { item[0]: GrimDawnItemData(code=item[2],can_create=(item[4] if item[4] is not None else (lambda world: True)),type=(item[1]),quantity=(item[3])) for index,item in enumerate(_item_data_list)}

item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
