from typing import Callable, Dict, NamedTuple, Optional

from BaseClasses import Location, MultiWorld

baseId = 219990
nlambda = None

class GrimDawnLocation(Location):
    game = "Grim Dawn"


class GrimDawnLocationData(NamedTuple):
    region: str
    address: Optional[int] = None
    can_create: Callable[[MultiWorld, int], bool] = lambda multiworld, player: True
    locked_item: Optional[str] = None

_location_data_list: list[tuple[str,str,Optional[Callable[[MultiWorld, int], bool]]]] = [
    ("Rescue Faldis",                                       "Act 1",                        None),
    ("Kill Reanimator",                                     "Act 1",                        None),
    ("Kasparov's Device",                                   "Act 1",                        None),
    ("Repair Waterpump",                                    "Act 1",                        None),
    ("Cleanse Slith Infestation",                           "Act 1",                        None),
    ("Free the Rovers",                                     "Act 1",                        None),
    ("Rescue Luther Graves",                                "Act 1",                        None),
    ("Secure Wightmire Portal",                             "Act 1",                        None),
    ("Secure Burrwitch Portal",                             "Act 1",                        None),
    ("Cultist in the Midst",                                "Act 1",                        None),
    ("Rescue Ulgrim",                                       "Act 1",                        None),
    ("Rescue Darlet",                                       "Act 1",                        None),
    ("Deal with the Hermit",                                "Act 1",                        None),
    ("A Tale of Two Blacksmiths",                           "Act 1",                        None),
    ("The Seamstress",                                      "Act 1",                        None),
    ("Kill Warden Krieg",                                   "Warden's Cellar",              None),
    ("Kill Edmund Shanks",                                  "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Family Crisis",                                       "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Quest for Vengeance",                                 "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Paying Tribute",                                      "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Frankie, The Knife",                                  "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Destroy the Forges",                                  "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Fetch Royal Jelly",                                   "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Moneybags Martin",                               "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Darius Cronely",                                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Destroy the Crystal",                                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Extortion Crisis",                                    "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Old Scars",                                           "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Kilrian",                                        "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Zarthuzellan, Grand Priest",                     "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Lutra the Abandoned",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Find Elsa",                                           "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Voldrak, the Destroyer",                         "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Too Late For Rescue",                                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Mogara, the Prime Matriarch",                    "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Ol' Bloodbriar",                                 "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Ungoliax, the Gloomweaver",                      "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Bloodfeast the Ruthless",                        "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Homestead Portal Secured",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Herald of the Flame",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Lost Armaments",                                      "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Chamber of Souls",                                    "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Alkamos, Lord Executioner",                      "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Door Guardian",                          "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Flames of Valbury",                                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Jarren the Plaguewarped",                        "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Van Aldritch",                                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Trapped and Alone",                                   "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill The Amalgamation",                               "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Kill Swarm Queen Ravna",                              "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 1)),
    ("Burn the Taken",                                      "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Blood Harvest",                                       "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Kill Bolvar, the Bloodbinder",                        "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("A Stranger in Need",                                  "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Clear the Lumber Mill",                               "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Kill Zaria, the Carver",                              "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Kill Karroz, Sigil of Ch'thon",                       "Darkvale Gate",                lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    ("Isaac's Stash",                                       "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Sunken Reliquary Exalted Stash",                      "Flooded Passage",              lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Depraved Sanctuary Exalted Stash",                    "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Monster's Hoard",                                     "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Hallowed Hill Exalted Stash",                         "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Ominous Lair Exalted Stash",                          "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Warden Krieg Exalted Stash",                          "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1)),
    ("Spined Cove Exalted Stash",                           "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Darius Cronley Exalted Stash",                        "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Swarming Hive Exalted Stash",                         "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovia Exalted Stash",                               "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Tyrant's Hold Exalted Stash",                         "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Misery Exalted Stash",                                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Conflagration Exalted Stash",                         "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Outskirts Exalted Chest",                "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Rotting Croplands Exalted Stash",                     "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Royal Hive Exalted Stash",                            "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Karroz's Exalted Stash",                              "Darkvale Gate",                lambda multiworld, player: (multiworld.worlds[player].options.one_shot.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Infested Cellar Secret Chest",                        "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Musty Cellar Secret Chest",                           "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Dank Cellar Secret Chest",                            "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Warden's Cellar South Secret Chest",                  "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Warden's Cellar Center Secret Chest",                 "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Abandoned Storerooms Secret Chest",                   "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Underground Transit Secret Chest",                    "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1)),
    ("Arkovian Foothills Southeast Secret Chest",           "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Foothills North Secret Chest",               "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Foothills Southwest Secret Chest",           "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Four Hills South Secret Chest 1",                     "New Harbor",                   lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Four Hills South Secret Chest 2",                     "New Harbor",                   lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Four Hills North Secret Chest",                       "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Hanneffy Mine Secret Chest",                          "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Cronley's Hideout South Secret Chest",                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Cronley's Hideout East Secret Chest",                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Coliseum Secret Chest",                      "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Twin Falls Secret Chest",                             "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Old Arkovia Secret Chest",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Undercity 2F West Secret Chest",             "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Undercity 2F North Secret Chest",            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Corrupted Tomb 2F Secret Chest",                      "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Broken Hills North Secret Chest",                     "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Broken Hills South Secret Chest",                     "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Steps of Torment Secret Chest",                       "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Pain Secret Chest",                                   "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Misery Secret Chest",                                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Suffering West Secret Chest",                         "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Suffering North Secret Chest",                        "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Anguish Secret Chest",                                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Arkovian Docks Secret Chest",                         "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Tyrant's Hold South Secret Chest",                    "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Tyrant's Hold Center Secret Chest",                   "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Tyrant's Hold North Secret Chest",                    "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Rotting Croplands North Secret Chest",                "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Rotting Croplands South Secret Chest",                "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Royal Hive Secret Chest",                             "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Secret Chest",                           "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Old Town Secret Chest",                  "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury High Town Secret Chest",                 "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Shrine of the Forgotten God North Secret Chest",      "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Shrine of the Forgotten God South Secret Chest",      "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Village of Darkvale Secret Chest",                    "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Darkvale Gate 1F South Secret Chest",                 "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Darkvale Gate 1F East Secret Chest",                  "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Darkvale Gate 2F East Secret Chest",                  "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Darkvale Gate 2F South Secret Chest",                 "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Darkvale Gate 2F North Secret Chest",                 "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.secret_chest.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Devotion Shrine - Burial Hill",                       "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Foggy Banks Cave",                  "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Burrwitch Outskirts Cave",          "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Flooded Passage",                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Burrwitch",                         "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Devil's Aquifer",                   "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Warden's Lab",                      "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - East Marsh",                        "East Marsh",                   lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1)),
    ("Devotion Shrine - Spined Cove",                       "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Rocky Coast",                       "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Cronley's Hideout",                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Old Arkovia",                       "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Arkovian Undercity",                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Misery",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Barren Highlands",                  "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Mountain Deeps",                    "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Forgotten Depths",                  "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Tyrant's Hold",                     "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Infested Farms",                    "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Den of the Lost",                   "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - The Conflagration",                 "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - Port Valbury Outskirts",            "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Devotion Shrine - The Blood Grove",                   "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Devotion Shrine - Village of Darkvale",               "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.devotion_shrine.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Crudely Scrawled Note",                               "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Francis' Note",                                       "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Harbormaster's Log - Lower Crossing",                 "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Hargate's Journal 1",                                 "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Milton Hart's Note",                                  "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Dirt-Covered Note",                                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Missive to Wightmire Bloodbound",                     "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("The Hidden Path - Dreeg",                             "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Writings of Rolderathis 1",                           "Flooded Passage",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Warden Krieg's Journal",                              "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Harbormaster's Log - Burrwitch",                      "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Alister's Diary",                                     "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Burrwitch Recon Report",                              "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 1",                                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 2",                                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 3",                                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 4",                                   "Act 1",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 5",                                   "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Creed's Journal 6",                                   "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Gethrand's Notes 1st Entry",                          "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Gethrand's Notes 2nd Entry",                          "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Gethrand's Notes Final Entry",                        "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Zanbrandt's Notes",                                   "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Missive to Warden Krieg",                             "Warden's Cellar",              lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Oboruuk's Journal 1",                                 "East Marsh",                   lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("The Gift of Ch'thon",                                 "East Marsh",                   lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Muddy Note",                                          "East Marsh",                   lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1)),
    ("Kymon's Scripture: First Passage",                    "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Dust Covered Journal",                                "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Wilkins' Note",                                       "Act 2",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Excerpt from the Annals of Arkovia",                  "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Coliseum Horrors",                                    "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Cronley's Notes - Part 1",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Malros Khas' Journal",                                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Last Days of Arkovia",                                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Cronley's Notes - Part 2",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Writings of Zarthuzellan",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Hidden Path - Solael",                            "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Ravings of Naren Kur",                                "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Bozeman's Folly",                                     "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Dangerous Roads",                                     "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("We're On Our Own",                                    "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Scales Strike Balance",                           "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Imperial Proclamation",                               "Desert",                       lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Journal of Duke Cavanil",                         "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Black Legion Scouting Report",                        "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Excerpt from Daila's Diary",                          "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Last Will of Marthos Everbrook",                  "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Walter's Note",                                       "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Elara's Journal",                                     "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Wald's Note",                                         "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Aether-Scorched Note",                                "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Amalgamation",                                    "Homestead Side Doors",         lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Inquisitor Creed - 7th Entry",             "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Inquisitor Creed - 8th Entry",             "Act 3",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The City is Rotting",                                 "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Mayor's Journal - Part 1",               "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Progress in Old Town",                                "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Paige Rehnaul - Part 1",                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Paige Rehnaul - Part 2",                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Paige Rehnaul - Part 3",                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("A Knife in the Dark",                                 "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Paige Rehnaul - Part 4",                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Journal of Paige Rehnaul - Part 5",                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Jarren's Journal - What Have I Done?",                "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Wanted Poster",                                       "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("The Same Dream Again",                                "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Port Valbury Mayor's Journal - Part 2",               "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Notice of Curfew",                                    "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("A Change of Plans",                                   "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("A Consensus Overruled",                               "Conflagration",                lambda multiworld, player: (multiworld.worlds[player].options.forbidden_dungeons.value == 1) and (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 1)),
    ("Scribe Osteram's Notes",                              "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Trevor's Note",                                       "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Mayor Bridgewater's Journal",                         "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Peacekeeper Chambre's Journal",                       "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("The Bath House",                                      "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Zaria's Journal - Page 1",                            "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Zaria's Journal - Page 2",                            "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Blood for Ch'thon",                                   "Act 4",                        lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
    ("Final Sermon: The End of Times",                      "Darkvale Gate",                lambda multiworld, player: (multiworld.worlds[player].options.lore.value == 1) and (multiworld.worlds[player].options.goal.value >= 2)),
]


location_data_table: Dict[str, GrimDawnLocationData] = { item[0]: GrimDawnLocationData(region=item[1],can_create=(item[2] if item[2] is not None else (lambda multiworld, player: True)),address=(baseId+index)) for index,item in enumerate(_location_data_list)}


location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}
locked_locations = {name: data for name, data in location_data_table.items() if data.locked_item}
