from typing import Dict, List, NamedTuple, Callable

from BaseClasses import MultiWorld

class GrimDawnRegionData(NamedTuple):
    connecting_regions: List[str] = []
    can_create: Callable[[MultiWorld, int], bool] = lambda multiworld, player: True


region_data_table: Dict[str, GrimDawnRegionData] = {
    "Menu":                     GrimDawnRegionData(connecting_regions=["Act 1 First Half"]),
    "Act 1 First Half":         GrimDawnRegionData(connecting_regions=["Sunken Reliquary","Act 2","Devil's Aquifer","Act 1 Second Half"]),
    "Act 1 Second Half":        GrimDawnRegionData(connecting_regions=["East Marsh","Warden's Cellar","Act 7"]),
    "Devil's Aquifer":          GrimDawnRegionData(connecting_regions=[]),
    "Sunken Reliquary":         GrimDawnRegionData(connecting_regions=[]),
    "East Marsh":               GrimDawnRegionData(connecting_regions=["Temple of the Three"]),
    "Warden's Cellar":          GrimDawnRegionData(connecting_regions=["Act 10"]),
    "Act 2":                    GrimDawnRegionData(connecting_regions=["Act 3"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    "Act 3":                    GrimDawnRegionData(connecting_regions=["Devil's Aquifer","Steps of Torment","Port Valbury","Four Hills Secret","Tyrant's Hold","Homestead Side Doors","Act 4"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    "Steps of Torment":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2) and (multiworld.worlds[player].options.forbidden_dungeons)),
    "Four Hills Secret":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2) and (multiworld.worlds[player].options.secret_chest)),
    "Tyrant's Hold":            GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    "Port Valbury":             GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2) and (multiworld.worlds[player].options.forbidden_dungeons)),
    "Homestead Side Doors":     GrimDawnRegionData(connecting_regions=["Royal Hive"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    "Royal Hive":               GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 2)),
    "Act 4":                    GrimDawnRegionData(connecting_regions=["Act 5","Frostveil Highlands"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Temple of the Three":      GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Act 5":                    GrimDawnRegionData(connecting_regions=["Act 6"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Act 6":                    GrimDawnRegionData(connecting_regions=["Tomb of the Watchers","Bastion of Chaos"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Bastion of Chaos":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.forbidden_dungeons)),
    "Tomb of the Watchers":     GrimDawnRegionData(connecting_regions=["Edge of Madness"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Edge of Madness":          GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3)),
    "Act 7":                    GrimDawnRegionData(connecting_regions=["Nane's Hideout","Ancient Grove","Forlorn Cellar","Den of the Ancient","Act 8"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Nane's Hideout":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4) and (multiworld.worlds[player].options.one_shot)),
    "Ancient Grove":            GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4) and (multiworld.worlds[player].options.forbidden_dungeons)),
    "Den of the Ancient":       GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Forlorn Cellar":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Act 8":                    GrimDawnRegionData(connecting_regions=["Candle District","Act 9"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Candle District":          GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Act 9":                    GrimDawnRegionData(connecting_regions=["Candle District","Harbor Stash","Crown Hill"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Harbor Stash":             GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4) and (multiworld.worlds[player].options.one_shot)),
    "Crown Hill":               GrimDawnRegionData(connecting_regions=["Fleshworks"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Fleshworks":               GrimDawnRegionData(connecting_regions=["Sanctum of Flesh"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Sanctum of Flesh":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 4)),
    "Act 10":                   GrimDawnRegionData(connecting_regions=["Act 11","Devil's Aquifer"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.dlc_fg)),
    "Act 11":                   GrimDawnRegionData(connecting_regions=["Devil's Aquifer","Lost Oasis","Tomb of the Eldritch Sun"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.dlc_fg.value)),
    "Lost Oasis":               GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.dlc_fg) and (multiworld.worlds[player].options.forbidden_dungeons)),
    "Tomb of the Eldritch Sun": GrimDawnRegionData(connecting_regions=["The Eldritch Gate"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.dlc_fg)),
    "The Eldritch Gate":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.dlc_fg)),
    
    "Frostveil Highlands":      GrimDawnRegionData(connecting_regions=["Icehowl Cavern","Icebound Passage"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Icehowl Cavern":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Icebound Passage":         GrimDawnRegionData(connecting_regions=["Freyoll Valley"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Freyoll Valley":           GrimDawnRegionData(connecting_regions=["Kurnhold"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Kurnhold":                 GrimDawnRegionData(connecting_regions=["Voldur River"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Voldur River":             GrimDawnRegionData(connecting_regions=["Blackheart's Hideout","Fekk's Burrow","Kurn Cellar","Ulo Springs"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Blackheart's Hideout":     GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Fekk's Burrow":            GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Kurn Cellar":              GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Ulo Springs":              GrimDawnRegionData(connecting_regions=["Ulo's Remorse","Lost Cairn Grotto","Kruu'Sul Crags","Ravager's Redoubt","Utak Kunar"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Ulo's Remorse":            GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Lost Cairn Grotto":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Utak Kunar":               GrimDawnRegionData(connecting_regions=["Bloodbound Bastion","Dread Wastes"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Dread Wastes":             GrimDawnRegionData(connecting_regions=["Crimson Expanse","Obsidian Wound","The World Tear","Glacial Grotto"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Crimson Expanse":          GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Obsidian Wound":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "The World Tear":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Glacial Grotto":           GrimDawnRegionData(connecting_regions=["Pilgrim's Rest"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Pilgrim's Rest":           GrimDawnRegionData(connecting_regions=["Black Lodge","Bitter Wind Pass"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Black Lodge":              GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Bitter Wind Pass":         GrimDawnRegionData(connecting_regions=["Scarstone Depths","Aurora Pinnacle"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Scarstone Depths":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Aurora Pinnacle":          GrimDawnRegionData(connecting_regions=["Glacierbound Cave","Rimespire Cavern","Windwalker's Den","Roof of the World"],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Glacierbound Cave":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Rimespire Cavern":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Windwalker's Den":         GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Roof of the World":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Kruu'Sul Crags":           GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Ravager's Redoubt":        GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
    "Bloodbound Bastion":       GrimDawnRegionData(connecting_regions=[],can_create=lambda multiworld, player: (multiworld.worlds[player].options.goal.value >= 3) and (multiworld.worlds[player].options.dlc_foa.value)),
}
